Add support for keras.layers.Dense in _get_word_embedding_weight
This resolves an issue of output embeddings in
`TFT5ModelTest.test_model_common_attributes` when
`model.config.tie_word_embeddings` is set to `False`:

```
AttributeError: 'Dense' object has no attribute 'kernel'
```